# @package _global_
dataset:
  # path: /data/chatgod/rvt_gen4/gen4/
  path: /home/pengys/Data/gen4/
wandb:
  project_name: SRVT
  group_name: 1mpx
hardware:
  gpus: [0, 1]
  num_workers:
    train: 6
    eval: 2
batch_size:
  train: 2
  eval: 2
benchmark: True
benchmark_only: False
use_test_set: True
model:
  backbone:
    partition_split_32: 2
    stage:
      attention:
        drop_mlp: 0.05
        drop_path: 0.05
training:
  precision: 16